[package]
name = "gengar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
poise = "0.6.1"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
